/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_package.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_clockgate.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_fifo.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_decompressor.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_control.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_regfile.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_cp_shifter.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_cp_muldiv.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_cp_bitmanip.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_cp_fpu.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_cp_cfu.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_cp_cond.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_alu.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_lsu.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu_pmp.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cpu.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_intercon.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cache.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_dma.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_imem.entity.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_dmem.entity.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_boot_rom.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_xip.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_xbus.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_cfs.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_sdi.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_gpio.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_wdt.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_mtime.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_uart.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_spi.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_twi.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_pwm.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_trng.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_neoled.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_xirq.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_gptmr.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_onewire.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_slink.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_crc.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_sysinfo.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_debug_dtm.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_debug_dm.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_top.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_bootloader_image.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/neorv32_application_image.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/mem/neorv32_imem.legacy.vhd
/home/aleksadj/Desktop/RISC_V_PROJECT/RISC_V_NEORV32/neorv32-main/neorv32-main/rtl/core/mem/neorv32_dmem.legacy.vhd
